frameworkVersion: ">=1.2.0 <2.0.0"
service: test-cognito

provider:
  name: aws
  runtime: nodejs6.10
  profile: madcore
  stage: dev
  region: eu-west-1

functions:
  igconito:
    handler: handler.getToken
    memorySize: 128
    timeout: 60
    events:
      - http:
          path: cognito_token/{userID}
          method: get
          integration: lambda-proxy
